Add infoboxes
Tslat/AoAWikiHelperMod pull request #75
Opened 2022-12-30 00:26 UTC by c64cosmin

https://github.com/Tslat/AoAWikiHelperMod/issues/33

2022-12-30 01:18 UTC, Tslat requested changes

2022-12-30 01:18 UTC, Tslat commented on src/main/java/net/tslat/aoawikihelpermod/command/ItemsCommand.java
> +	public static class ItemArgument implements ArgumentType<ItemInput> {
Why are we creating another ItemArgument?
One already exists in net.minecraft.commands.arguments.item.ItemArgument

2022-12-30 01:18 UTC, Tslat commented on src/main/java/net/tslat/aoawikihelpermod/command/ItemsCommand.java
> +	public static final Map<String, Class<? extends ItemArgumentByType>> ITEM_ARGUMENT_CLASSES = Map.ofEntries(
Don't do this.
Make a SuggestionProvider that filters out in a stream based on the argument in the command via CommandContext
See: TradesCommand#43 for a SuggestionProvider, you can then filter the stream using the CommandContext

2022-12-30 01:18 UTC, Tslat commented on src/main/java/net/tslat/aoawikihelpermod/command/ItemsCommand.java
> +	public static class ItemArgumentTypeBlaster extends ItemArgumentByType {
These outright shouldn't exist - there's a generic form for them already in place, and you should be filtering by an argument, not a hardcoded class

2022-12-30 01:18 UTC, Tslat commented on src/main/java/net/tslat/aoawikihelpermod/util/ObjectHelper.java
> +	public static String getItemNameFromItem(Item item){
This already exists in ObjectHelper#getItemName

2022-12-30 01:18 UTC, Tslat commented on src/main/java/net/tslat/aoawikihelpermod/command/InfoboxCommand.java
> +		builder.then(
Please use consistent formatting with the existing commands.

2022-12-30 01:18 UTC, Tslat commented on src/main/java/net/tslat/aoawikihelpermod/util/printers/infoboxes/ItemInfoboxPrintHelper.java
> +	private static String convertRarityColor(Rarity rarity) {
This should be a StringUtil.toTitleCase call, not its own method

2022-12-30 01:18 UTC, Tslat commented on src/main/java/net/tslat/aoawikihelpermod/util/printers/infoboxes/ItemInfoboxPrintHelper.java
> +	private static String getSaturation(ItemStack itemStack, Entity entity) {
If this expects a LivingEntity, why is it typed Entity?

2022-12-30 01:18 UTC, Tslat commented on src/main/java/net/tslat/aoawikihelpermod/util/printers/infoboxes/ItemInfoboxPrintHelper.java
> +		if (value > 0) return NumberUtil.roundToNthDecimalPlace((float) (value + offset), 2) + suffix;
Please use consistent formatting

Single-line returns are not used in WikiHelper

2022-12-30 01:24 UTC, c64cosmin commented on src/main/java/net/tslat/aoawikihelpermod/command/ItemsCommand.java
> +	public static class ItemArgument implements ArgumentType<ItemInput> {
This is how BlockArgument is done in BlocksCommand, I just replicated the pattern.
I suppose net.minecraft.commands.arguments.item.ItemArgument returns Minecraft items
while we need to only list from ForgeRegistries.ITEMS
Should I use that one and use SuggestionProvider?

2022-12-30 01:26 UTC, c64cosmin commented on src/main/java/net/tslat/aoawikihelpermod/util/ObjectHelper.java
> +	public static String getItemNameFromItem(Item item){
For some strange reason this initially gave me compilation errors, deleting it now.
Might have mistakenly provided an ItemStack as parameter.

2022-12-30 01:27 UTC, Tslat commented on src/main/java/net/tslat/aoawikihelpermod/command/ItemsCommand.java
> +	public static class ItemArgument implements ArgumentType<ItemInput> {
Leave it and I'll take a closer look after merge and let you know

2022-12-30 01:31 UTC, c64cosmin commented on src/main/java/net/tslat/aoawikihelpermod/util/printers/infoboxes/ItemInfoboxPrintHelper.java
> +	private static String convertRarityColor(Rarity rarity) {
Not clear, that is duplicated from this
https://github.com/Tslat/AoAWikiHelperMod/blob/1.19/src/main/java/net/tslat/aoawikihelpermod/util/printers/infoboxes/BlockInfoboxPrintHelper.java#L117-L125

2022-12-30 01:33 UTC, Tslat commented on src/main/java/net/tslat/aoawikihelpermod/util/printers/infoboxes/ItemInfoboxPrintHelper.java
> +	private static String convertRarityColor(Rarity rarity) {
Yeah the original BlockInfobox thing wasn't really looked into much, and it was implemented by fuji, not myself
It needed its own review which we never did because I didn't have time to look into infoboxes myself yet

Don't take BlockInfoboxPrintHelper as gospel ;)

2022-12-30 18:58 UTC, c64cosmin commented on src/main/java/net/tslat/aoawikihelpermod/command/ItemsCommand.java
> +	public static final Map<String, Class<? extends ItemArgumentByType>> ITEM_ARGUMENT_CLASSES = Map.ofEntries(
SuggestionProvider worked like a charm, now all is using generics and an array of categories

2022-12-30 18:58 UTC, c64cosmin commented on src/main/java/net/tslat/aoawikihelpermod/command/ItemsCommand.java
> +	public static class ItemArgumentTypeBlaster extends ItemArgumentByType {
Lol, removed :rofl:

2022-12-30 19:20 UTC, c64cosmin commented on src/main/java/net/tslat/aoawikihelpermod/command/InfoboxCommand.java
> +		builder.then(
Without break the parenthesis the code is not easy to read, I don't know how to format this other than being on a single line. .execute is in the inner parenthesis, so this way it is clearer what happens

2022-12-30 20:38 UTC, Tslat commented on src/main/java/net/tslat/aoawikihelpermod/command/InfoboxCommand.java
> +		builder.then(
I'll fix it after merge then

2022-12-31 13:49 UTC, c64cosmin commented on src/main/java/net/tslat/aoawikihelpermod/command/InfoboxCommand.java
> +		builder.then(
Read some more code, now I understand what formatting you were talking about.

2022-12-31 14:24 UTC, c64cosmin commented on src/main/java/net/tslat/aoawikihelpermod/command/ItemsCommand.java
> +	public static class ItemArgument implements ArgumentType<ItemInput> {
I can replace all this code with the SuggestionProvider, it is more compact as code

2023-01-03 04:38 UTC, Tslat approved these changes

2023-01-03 04:38 UTC, merged